// +build !ignore_autogenerated

// gen

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CountUnique) DeepCopyInto(out *CountUnique) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CountUnique.
func (in *CountUnique) DeepCopy() *CountUnique {
	if in == nil {
		return nil
	}
	out := new(CountUnique)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CountUnique) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CountUniqueList) DeepCopyInto(out *CountUniqueList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CountUnique, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CountUniqueList.
func (in *CountUniqueList) DeepCopy() *CountUniqueList {
	if in == nil {
		return nil
	}
	out := new(CountUniqueList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CountUniqueList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CountUniqueSpec) DeepCopyInto(out *CountUniqueSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CountUniqueSpec.
func (in *CountUniqueSpec) DeepCopy() *CountUniqueSpec {
	if in == nil {
		return nil
	}
	out := new(CountUniqueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CountUniqueStatus) DeepCopyInto(out *CountUniqueStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CountUniqueStatus.
func (in *CountUniqueStatus) DeepCopy() *CountUniqueStatus {
	if in == nil {
		return nil
	}
	out := new(CountUniqueStatus)
	in.DeepCopyInto(out)
	return out
}
