apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: countuniques.lekva.me
spec:
  group: lekva.me
  scope: Namespaced
  names:
    kind: CountUnique
    listKind: CountUniqueList
    plural: countuniques
    singular: countunique
    shortNames:
      - cu
      - cus
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                startFrom:
                  type: string
                numDocuments:
                  type: integer
                numBits:
                  type: integer
            status:
              type: object
              properties:
                state:
                  type: string
                message:
                  type: string
